version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "08:30"
    timezone: America/New_York
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 6.20.17
    - 6.20.18
    - 6.20.19
    - 6.20.20
    - 6.20.22
    - 6.20.23
    - 6.20.24
    - 6.20.25
  - dependency-name: symfony/error-handler
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.19
  - dependency-name: orchestra/testbench
    versions:
    - 4.15.0
  - dependency-name: art4/json-api-client
    versions:
    - 0.10.2
  rebase-strategy: disabled
